name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite executar manualmente pelo GitHub

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 [1]

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" [1]

      - name: Go mod tidy
        run: go mod tidy [1]

      - name: Build
        run: go build -v ./... [1, 2]

      - name: Test
        # O "|| true" garante que a pipeline não para se ainda não existirem testes unitários
        run: go test -v ./... || true [1, 2]

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy (SSH)
        uses: appleboy/ssh-action@v1.0.3 [1]
        with:
          host: ${{ secrets.VM_HOST }} [1, 3]
          username: ${{ secrets.VM_USER }} [1, 3]
          key: ${{ secrets.VM_SSH_KEY }} [1, 3]
          script: |
            bash /home/appuser/deploy.sh [1, 3]
